UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/tallyBillList?from=oldsystem',server_addr='' WHERE authority_name='理货单列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/purchaseWarehouseList?from=oldsystem',server_addr='' WHERE authority_name='采购入库列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/predeclarationList?from=oldsystem',server_addr='' WHERE authority_name='预申报单列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/crossCheckDetailList?from=oldsystem',server_addr='' WHERE authority_name='采购入库勾稽明细表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/differenceAnalysisList?from=oldsystem',server_addr='' WHERE authority_name='采购入库差异分析表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/orderTrackeList?from=oldsystem',server_addr='' WHERE authority_name='采购订单跟踪报表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/returnGoodsList?from=oldsystem',server_addr='' WHERE authority_name='采购退货列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/purchase/exWarehouseList?from=oldsystem',server_addr='' WHERE authority_name='采购退货出库列表'

UPDATE st_permission_info SET url='http://depx.topideal.mobi/allocation/tallyList?from=oldsystem',server_addr='' WHERE authority_name='调拨理货单列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/allocation/deliveryList?from=oldsystem',server_addr='' WHERE authority_name='调拨出库列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/allocation/warehouseList?from=oldsystem',server_addr='' WHERE authority_name='调拨入库列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/allocation/transferFlow?from=oldsystem',server_addr='' WHERE authority_name='调出调入流水'

UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/salesdelivery?from=oldsystem',server_addr='' WHERE authority_name='销售出库清单'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/salesdifference?from=oldsystem',server_addr='' WHERE authority_name='销售出库差异分析表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/salesreturnorder?from=oldsystem',server_addr='' WHERE authority_name='销售退货订单列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/returnreceiptorder?from=oldsystem',server_addr='' WHERE authority_name='销售退货入库清单'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/returndeliveryorder?from=oldsystem',server_addr='' WHERE authority_name='销售退货出库清单'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/returntallyorder?from=oldsystem',server_addr='' WHERE authority_name='销售退货理货单列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/salesoutbound?from=oldsystem',server_addr='' WHERE authority_name='销售出库明细表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/shelveslist?from=oldsystem',server_addr='' WHERE authority_name='上架列表'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/sales/salescrosscheck?from=oldsystem',server_addr='' WHERE authority_name='预售勾稽列表'

UPDATE st_permission_info SET url='http://depx.topideal.mobi/warehousefile/AreaConfig?from=oldsystem',server_addr='' WHERE authority_name='关区配置'
UPDATE st_permission_info SET url='http://depx.topideal.mobi/companyFile/TaxRateConfig?from=oldsystem',server_addr='' WHERE authority_name='税率配置'
